// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

import Footer from "../Components/footer";
import Navbar from "../Components/navbar";
import "./globals.css";


// import Header from "@/Components/Header";  {/* Rafce3.tsx */}

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Header/> */}     {/* Rafce3.tsx */}
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
